---
---
title: "norming analysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)
library(dplyr)
```

```{r}

data = read.csv("./norming_csv.csv")


data %>%
  group_by(context) %>%
  summarize(many_m = mean(many)) %>%
  ggplot(aes(x=context, y=many_m*100)) +
  xlab("number of apples")+
  ylab("Percentage of people who responded 'too much'")+
  ggtitle("Number of apples v Many/Few Sentiment")+
  theme(plot.title = element_text(hjust = 0.5))+
  geom_point()+
  geom_smooth()

data %>%
  group_by(context) %>%
  summarize(confidence_m = mean(confidence)) %>%
  ggplot(aes(x=context, y=confidence_m)) +
  xlab("number of apples")+
  ylab("Percentage of people who responded 'appropriate'")+
  ggtitle("Number of apples v Confidence")+
  theme(plot.title = element_text(hjust = 0.5))+
  geom_point()+
  geom_smooth()

data %>%
  group_by(many) %>%
  summarize(confidence_m = mean(confidence)) %>%
  ggplot(aes(x=many, y=confidence_m)) +
  xlab("number of apples")+
  ylab("Percentage of people who responded 'appropriate'")+
  ggtitle("Number of apples v Confidence")+
  theme(plot.title = element_text(hjust = 0.5))+
  geom_point()


```





